[package]
name = "fishsense_core"
version = "2.1.5"
edition = "2024"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fishsense_core"
crate-type = ["cdylib"]

[features]
cuda = ["fishsense-core/cuda"]

[build-dependencies]
cc = "1"

[dependencies]
fishsense-core = { path = "../../rust/fishsense-core" }
ndarray = "0.17.1"
numpy = "0.27.1"
pyo3 = "0.27.0"
pyo3-log = "0.13"
tracing-log = "0.2"
