name: Python

on: [push]

defaults:
  run:
    working-directory: python/fishsense_core

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mesa-vulkan-drivers libvulkan1 clang libclang-dev libopencv-dev
        python -m pip install --upgrade pip uv
        uv sync --group dev
    - name: Analysing the code with pylint
      run: uv run pylint fishsense_core/**/*.py

  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.14"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv
        uv sync --group dev
    - name: Run tests
      run: uv run pytest --cov=fishsense_core --cov-report=xml --cov-report=html
